version: '3'

services:
  api:
    container_name: api
    image: myriadsocial/myriad-api
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    ports:
      - 3003:3000
    networks:
      myriad:
        ipv4_address: 172.27.3.3
        aliases:
          - api

networks:
  myriad:
    external: true
