version: '3'

services:
  web:
    container_name: myriad-api
    image: myriadsocial/myriad-api
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3001:3000
    networks:
      myriad:
        ipv4_address: 172.27.1.3
        aliases:
          - myriad-api

networks:
  myriad:
    external: true
