version: '3'

services:
  api:
    container_name: myriad-api
    image: myriadsocial/myriad-api
    build:
      context: ../../
      dockerfile: Dockerfile
    volumes:
      - ../../:/home/myriad/app
      - /home/myriad/app/node_modules
      - /home/myriad/app/dist
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3001:3000
    networks:
      myriad:
        ipv4_address: 172.27.1.4
        aliases:
          - api

networks:
  myriad:
    external: true
