version: '3'

services:
  api:
    image: myriadsocial/myriad-api:1.0.0
    environment:
      - PORT=3000
      - MYRIAD_WS_RPC=ws://parachain-alice:9944
      - MYRIAD_CRYPTO_TYPE=sr25519
      - MYRIAD_ADDRESS_PREFIX=214
      - MYRIAD_FAUCET_MNEMONIC=gown bless stove mind foam nephew also rebel live half setup thunder
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=api
      - MONGO_PASSWORD=passw0rd
      - MONGO_DATABASE=myriad
      - FIREBASE_PROJECT_ID=
      - FIREBASE_CLIENT_EMAIL=
      - FIREBASE_PRIVATE_KEY=
      - TWITTER_BEARER_TOKEN=
    ports:
      - 3001:3000
    networks:
      myriad:
        ipv4_address: 172.27.1.7
        aliases:
          - api

networks:
  myriad:
    external: true
