apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myriad-api.fullname" . }}
  labels:
    {{- include "myriad-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "myriad-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "myriad-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "myriad-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYRIAD_WS_RPC
              value: {{ .Values.config.rpcWSURL }}
            - name: MYRIAD_FAUCET_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-api.baseSecretName" . }}
                  key: faucetMnemonic
            - name: MYRIAD_REWARD_AMOUNT
              value: {{ .Values.config.rewardAmount }}
            - name: MONGO_HOST
              value: {{ .Values.config.mongo.host }}
            - name: MONGO_PORT
              value: {{ .Values.config.mongo.port }}
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-api.mongoSecretName" . }}
                  key: user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-api.mongoSecretName" . }}
                  key: password
            - name: MONGO_DATABASE
              value: {{ .Values.config.mongo.database }}
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-api.firebaseSecretName" . }}
                  key: projectId
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-api.firebaseSecretName" . }}
                  key: clientEmail
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-api.firebaseSecretName" . }}
                  key: privateKey
            - name: TWITTER_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "myriad-api.twitterSecretName" . }}
                  key: bearerToken
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 25
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
