{{ if .Values.issuer.createTLSCertificateIssuer -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-api
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.issuer.tlsCertificateIssuerEmail }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-api
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}
