apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.baseSecretName" . }}
type: Opaque
data:
  faucetMnemonic: {{ .Values.config.faucetMnemonic | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.mongoSecretName" . }}
type: Opaque
data:
  user: {{ .Values.config.mongo.user | b64enc }}
  password: {{ .Values.config.mongo.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.firebaseSecretName" . }}
type: Opaque
data:
  projectId: {{ .Values.config.firebase.projectId | b64enc }}
  clientEmail: {{ .Values.config.firebase.clientEmail | b64enc }}
  privateKey: {{ .Values.config.firebase.privateKey | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.twitterSecretName" . }}
type: Opaque
data:
  bearerToken: {{ .Values.config.twitter.bearerToken | b64enc }}
