apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.faucetSecretName" . }}
type: Opaque
data:
  faucetMnemonic: {{ .Values.config.faucetMnemonic | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.mongoSecretName" . }}
type: Opaque
data:
  user: {{ .Values.config.mongo.user | b64enc }}
  password: {{ .Values.config.mongo.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.firebaseSecretName" . }}
type: Opaque
data:
  serviceAccount: {{ .Values.config.firebase.serviceAccountBase64 }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.twitterSecretName" . }}
type: Opaque
data:
  bearerToken: {{ .Values.config.twitter.bearerToken | b64enc }}
