{{- if .Values.config.faucetMnemonic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.faucetSecretName" . }}
type: Opaque
data:
  faucetMnemonic: {{ .Values.config.faucetMnemonic | b64enc }}

---
{{- end }}
{{- if and .Values.config.mongo.user .Values.config.mongo.password }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.mongoSecretName" . }}
type: Opaque
data:
  user: {{ .Values.config.mongo.user | b64enc }}
  password: {{ .Values.config.mongo.password | b64enc }}

---
{{- end }}
{{- if .Values.config.firebase.serviceAccountBase64 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.firebaseSecretName" . }}
type: Opaque
data:
  serviceAccount: {{ .Values.config.firebase.serviceAccountBase64 }}

---
{{- end }}
{{- if .Values.config.sentry.dns }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.sentrySecretName" . }}
type: Opaque
data:
  dns: {{ .Values.config.sentry.dns | b64enc }}

---
{{- end }}
{{- if .Values.config.twitter.bearerToken }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-api.twitterSecretName" . }}
type: Opaque
data:
  bearerToken: {{ .Values.config.twitter.bearerToken | b64enc }}
{{- end }}
