export enum ActivityLogType {
  CREATEUSERNAME = 'username',
  UPLOADPROFILEPICTURE = 'upload_profile_picture',
  FILLBIO = 'fill_in_bio',
  UPLOADBANNER = 'upload_banner',
  SKIPUSERNAME = 'skip_new_user_username',
  SENDTIP = 'send_tip',
  IMPORTPOST = 'import_post',
  CLAIMSOCIAL = 'claim_social_media',
  GIVEVOTE = 'give_vote',
  FRIENDREQUEST = 'friend_request',
  CREATEEXPERIENCE = 'create_experience',
  SUBSCRIBEEXPERIENCE = 'subscribe_experience',
  CLAIMTIP = 'claim_tip',
  CREATEPOST = 'create_post',
  CREATECOMMENT = 'create_comment',
}
