export enum ControllerType {
  USER = 'UserController',
  POST = 'PostController',
  TRANSACTION = 'TransactionController',
  EXPERIENCE = 'ExperienceController',
  PEOPLE = 'PeopleController',
  TAG = 'TagController',
  NOTIFICATION = 'NotificationController',
  CURRENCY = 'CurrencyController',
  USERCURRENCY = 'UserCurrencyController',
  USERSOCIALMEDIA = 'UserSocialMediaController',
  USEREXPERIENCE = 'UserExperienceController',
  FRIEND = 'FriendController',
  COMMENT = 'CommentController',
  ACTIVITYLOG = 'ActivityLogController',
  REPORT = 'ReportController',
  DELETEDCOLLECTION = 'DeletedCollectionController',
  USERREPORTCONTROLLER = 'UserReportController',
  REPORTUSER = 'ReportUserController',
  LEADERBOARD = 'LeaderBoardController',
}

export enum MethodType {
  FIND = 'find',
  FINDBYID = 'findById',
  CREATE = 'create',
  CREATEVOTE = 'createVote',
  UPDATEBYID = 'updateById',
  UPDATEEXPERIENCE = 'updateExperience',
  TIMELINE = 'getTimeline',
  VERIFY = 'verify',
  SUBSCRIBE = 'subscribe',
  CREATENEW = 'createNew',
  RESTORE = 'restore',
  DELETE = 'delete',
  DELETEBYID = 'deleteById',
  DELETEDPOSTLIST = 'deletedPostList',
  DELETEDUSERLIST = 'deletedUserList',
  SELECTCURRENCY = 'selectCurrency',
  GETIMPORTERS = 'getImporters',
  MUTUALDETAIL = 'mutualDetail',
}
