export enum ControllerType {
  USER = 'UserController',
  POST = 'PostController',
  TRANSACTION = 'TransactionController',
  EXPERIENCE = 'ExperienceController',
  PEOPLE = 'PeopleController',
  TAG = 'TagController',
  NOTIFICATION = 'NotificationController',
  CURRENCY = 'CurrencyController',
  USERCURRENCY = 'UserCurrencyController',
  USERSOCIALMEDIA = 'UserSocialMediaController',
  USEREXPERIENCE = 'UserExperienceController',
  FRIEND = 'FriendController',
  COMMENT = 'CommentController',
  ACTIVITYLOG = 'ActivityLogController',
  REPORT = 'ReportController',
  DELETEDCOLLECTION = 'DeletedCollectionController',
  USERREPORT = 'UserReportController',
  REPORTUSER = 'ReportUserController',
  AUTHENTICATION = 'AuthenticationController',
  USERACCOUNTSETTING = 'UserAccountSettingController',
  USERNOTIFICATIONSETTING = 'UserNotificationSettingController',
  VOTE = 'VoteController',
}

export enum MethodType {
  FIND = 'find',
  FINDBYID = 'findById',
  CREATE = 'create',
  PATCH = 'patch',
  CREATEVOTE = 'createVote',
  UPDATEBYID = 'updateById',
  UPDATEEXPERIENCE = 'updateExperience',
  TIMELINE = 'getTimeline',
  VERIFY = 'verify',
  SUBSCRIBE = 'subscribe',
  CREATENEW = 'createNew',
  RESTORE = 'restore',
  DELETE = 'delete',
  DELETEBYID = 'deleteById',
  DELETEDPOSTLIST = 'deletedPostList',
  DELETEDUSERLIST = 'deletedUserList',
  SELECTCURRENCY = 'selectCurrency',
  SELECTEXPERIENCE = 'selectExperience',
  GETIMPORTERS = 'getImporters',
  MUTUALDETAIL = 'mutualDetail',
  LEADERBOARD = 'leaderboard',
  RECOVERPOST = 'recoverPost',
  RECOVERUSER = 'recoverUser',
  READNOTIFICATION = 'readNotification',
  READMULTIPLENOTIFICATION = 'readMultipleNotification',
  UPDATEPRIMARY = 'updatePrimary',
  IMPORT = 'import',
}
