export enum ControllerType {
  USER = 'UserController',
  POST = 'PostController',
  TRANSACTION = 'TransactionController',
  EXPERIENCE = 'ExperienceController',
  PEOPLE = 'PeopleController',
  TAG = 'TagController',
  NOTIFICATION = 'NotificationController',
  CURRENCY = 'CurrencyController',
  USERCURRENCY = 'UserCurrencyController',
  USERSOCIALMEDIA = 'UserSocialMediaController',
  USEREXPERIENCE = 'UserExperienceController',
  FRIEND = 'FriendController',
  COMMENT = 'CommentController',
  ACTIVITYLOG = 'ActivityLogController',
  REPORT = 'ReportController',
  DELETEDCOLLECTION = 'DeletedCollectionController',
  USERREPORT = 'UserReportController',
  REPORTUSER = 'ReportUserController',
  AUTHENTICATION = 'AuthenticationController',
  USERACCOUNTSETTING = 'UserAccountSettingController',
  USERNOTIFICATIONSETTING = 'UserNotificationSettingController',
  USERDRAFTPOST = 'UserDraftPostController',
  STORAGECONTROLLER = 'StorageController',
  TIPCONTROLLER = 'TipController',
  VOTE = 'VoteController',
}
