export enum NotificationType {
  COMMENT_COMMENT = 'comment_comment',
  COMMENT_MENTION = 'comment_mention',
  COMMENT_REMOVED = 'comment_removed',
  COMMENT_TIPS = 'comment_tips',
  COMMENT_VOTE = 'comment_vote',
  CONNECTED_SOCIAL_MEDIA = 'connected_social_media',
  DISCONNECTED_SOCIAL_MEDIA = 'disconnected_social_media',
  FRIEND_ACCEPT = 'friend_accept',
  FRIEND_REQUEST = 'friend_request',
  POST_COMMENT = 'post_comment',
  POST_MENTION = 'post_mention',
  POST_REMOVED = 'post_removed',
  POST_TIPS = 'post_tips',
  POST_VOTE = 'post_vote',
  USER_BANNED = 'user_banned',
  USER_CLAIM_TIPS = 'user_claim_tips',
  USER_INITIAL_TIPS = 'user_initial_tips',
  USER_REWARD = 'user_reward',
  USER_TIPS = 'user_tips',
}
