import {intercept, service} from '@loopback/core';
import {Filter, FilterExcludingWhere, repository} from '@loopback/repository';
import {
  get,
  getModelSchemaRef,
  HttpErrors,
  param,
  patch,
  post,
  requestBody,
  response,
} from '@loopback/rest';
import {BcryptHasher} from '../services/authentication/hash.password.service';
import {ActivityLogType} from '../enums';
import {DeletedDocument, PaginationInterceptor} from '../interceptors';
import {User} from '../models';
import {UserRepository} from '../repositories';
import {ActivityLogService} from '../services';
// import {authenticate} from '@loopback/authentication';

// @authenticate("jwt")
export class UserController {
  constructor(
    @repository(UserRepository)
    protected userRepository: UserRepository,
    @service(ActivityLogService)
    protected activityLogService: ActivityLogService,
  ) {}

  @post('/users')
  @response(200, {
    description: 'User model instance',
    content: {
      'application/json': {
        schema: getModelSchemaRef(User),
      },
    },
  })
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {
            title: 'NewUser',
            exclude: [
              'profilePictureURL',
              'bannerImageUrl',
              'fcmTokens',
              'onTimeline',
              'createdAt',
              'updatedAt',
              'deletedAt',
              'autoGeneratedPassword',
            ],
          }),
        },
      },
    })
    user: User,
  ): Promise<User> {
    //TODO: override the default create() method and move password auto-generation there
    //auto-generate a password by hashing the user's id
    const hasher = new BcryptHasher();
    user.password = await hasher.hashPassword(user.id);
    return this.userRepository.create(user);
  }

  @intercept(PaginationInterceptor.BINDING_KEY)
  @get('/users')
  @response(200, {
    description: 'Array of User model instances',
    content: {
      'application/json': {
        schema: {
          type: 'array',
          items: getModelSchemaRef(User, {includeRelations: true}),
        },
      },
    },
  })
  async find(
    @param.filter(User, {exclude: ['limit', 'skip', 'offset']})
    filter?: Filter<User>,
  ): Promise<User[]> {
    return this.userRepository.find(filter);
  }

  @intercept(DeletedDocument.BINDING_KEY)
  @get('/users/{id}')
  @response(200, {
    description: 'User model instance',
    content: {
      'application/json': {
        //TODO: hide password from response
        schema: getModelSchemaRef(User, {includeRelations: true}),
      },
    },
  })
  async findById(
    @param.path.string('id') id: string,
    @param.filter(User, {exclude: 'where'}) filter?: FilterExcludingWhere<User>,
  ): Promise<User> {
    return this.userRepository.findById(id, filter);
  }

  @patch('/users/{id}')
  @response(204, {
    description: 'User PATCH success',
  })
  async updateById(
    @param.path.string('id') id: string,
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {
            partial: true,
            exclude: ['id', 'defaultCurrency', 'onTimeline', 'deletedAt'],
          }),
        },
      },
    })
    user: Partial<User>,
  ): Promise<void> {
    if (user.username) {
      this.validateUsername(user.username);

      await this.activityLogService.userProfileActivityLog(
        ActivityLogType.CREATEUSERNAME,
        id,
      );
    }

    if (user.profilePictureURL) {
      await this.activityLogService.userProfileActivityLog(
        ActivityLogType.UPLOADPROFILEPICTURE,
        id,
      );
    }

    if (user.bannerImageUrl) {
      await this.activityLogService.userProfileActivityLog(
        ActivityLogType.UPLOADBANNER,
        id,
      );
    }

    if (user.bio) {
      await this.activityLogService.userProfileActivityLog(
        ActivityLogType.FILLBIO,
        id,
      );
    }

    await this.userRepository.updateById(id, user);
  }

  @post('/users/{id}/skip-username')
  @response(200, {
    description: 'Skip username success',
  })
  async skipUsername(@param.path.string('id') id: string): Promise<void> {
    const found = await this.userRepository.activityLogs(id).find({
      where: {
        type: ActivityLogType.SKIPUSERNAME,
      },
    });

    if (found.length >= 1) {
      throw new HttpErrors.UnprocessableEntity(
        'You have already skip updating username',
      );
    }

    await this.userRepository.activityLogs(id).create({
      type: ActivityLogType.SKIPUSERNAME,
      message: 'You skipped updating username',
      userId: id,
    });

    return;
  }

  validateUsername(username: string): void {
    if (
      username[username.length - 1] === '.' ||
      username[username.length - 1] === '_'
    ) {
      throw new HttpErrors.UnprocessableEntity(
        'Last character must be an ascii letter (a-z) or number (0-9)',
      );
    }

    if (username[0] === '.' || username[0] === '_') {
      throw new HttpErrors.UnprocessableEntity(
        'Character must be start from an ascii letter (a-z) or number (0-9)',
      );
    }

    if (username.includes('.') && username.includes('_')) {
      throw new HttpErrors.UnprocessableEntity(
        'Only allowed ascii letter (a-z), number (0-9), and periods(.)/underscore(_)',
      );
    }

    if (!username.match('^[a-z0-9._]+$')) {
      throw new HttpErrors.UnprocessableEntity(
        'Only allowed ascii letter (a-z), number (0-9), and periods(.)/underscore(_)',
      );
    }
  }
}
