name: SAST

on:
  pull_request:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: sast-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript
          - typescript
    runs-on: ubuntu-20.04
    name: CodeQL ( ${{ matrix.language }} )
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Initialize
        uses: github/codeql-action/init@f3feb00acb00f31a6f60280e6ace9ca31d91c76a
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@f3feb00acb00f31a6f60280e6ace9ca31d91c76a
      - name: Analize
        uses: github/codeql-action/analyze@f3feb00acb00f31a6f60280e6ace9ca31d91c76a
