name: SAST

on:
  pull_request:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: sast-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript
          - typescript
    runs-on: ubuntu-20.04
    name: CodeQL ( ${{ matrix.language }} )
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Initialize
        uses: github/codeql-action/init@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@cdcdbb579706841c47f7063dda365e292e5cad7a
      - name: Analize
        uses: github/codeql-action/analyze@cdcdbb579706841c47f7063dda365e292e5cad7a
