name: Tester

on:
  pull_request:

concurrency:
  group: tester-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test code
        run: yarn test
