name: Tester

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.maintain/**'
      - '.dockerignore'
      - '.env-template'
      - 'LICENSE'

concurrency:
  group: tester-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.filter.outputs.test }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            test:
              - '.husky'
              - 'public/**'
              - 'src/**'
              - '.editorconfig'
              - '.eslintignore'
              - '.eslintrc.js'
              - '.gitignore'
              - '.lintstagedrc.json'
              - '.mocharc.json'
              - '.prettierignore'
              - '.prettierrc.json'
              - '.yo-rc.json'
              - 'package.json'
              - 'tsconfig.json'
              - 'yarn.lock'
            markdown:
              - 'docs/**'
              - 'DEVELOPING.md'
              - 'README.md'

  test-code:
    needs: changes
    if: ${{ needs.changes.outputs.test == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test code
        run: yarn test

  check-link-markdown:
    needs: changes
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check link markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/mlc_config.json'
